name: apexmsenscalc
description: This Application help Apex Mobile Gamers to improve gameplay by adjusting camera sensitivity and gyroscope sensitivity.

publish_to: 'none' 

version: 0.5.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  get_storage: ^2.0.3
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.1
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"

flutter:
  uses-material-design: true
  assets:
  - assets/icons/app_logo.png
  - assets/images/gyroscope.png
  - assets/images/tap.png
  - assets/images/howtouse/  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
